Create CONTRIBUTING
Askia/.github pull request #2
Opened 2024-11-20 13:54 UTC by MamadouSy

Add a generic page to explain how to contribute.

2024-11-20 14:54 UTC, catalin-mihai-p5 approved these changes

2024-11-21 11:49 UTC, vladimirp5 requested changes
Here's a reference link to the best practices and code smells doc that I've created in the Documentation repository and which should be included in your PR.

https://github.com/Askia/Documentation/blob/best-practices-and-code-smells/Development/best-practices-and-code-smells.md

2024-11-28 09:14 UTC, MamadouSy commented
> Here's a reference link to the best practices and code smells doc that I've created in the Documentation repository and which should be included in your PR.
> 
> https://github.com/Askia/Documentation/blob/best-practices-and-code-smells/Development/best-practices-and-code-smells.md

I'll merge that one and will do another PR once the "Documentation" will be merge (I don't want to put a link to a branch).

2024-11-28 09:29 UTC, vladimirp5 approved these changes

2024-11-28 09:39 UTC, merged